# Generated by Django 3.0.2 on 2020-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20200217_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='album_id',
            new_name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=200, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
