# Generated by Django 3.0.2 on 2020-02-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20200217_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=200, verbose_name='описание альбома'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.Album', verbose_name='альбом'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=200, verbose_name='описаните картинки'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
